<template>
  <section class="admin-evolution">
    <el-tabs v-model="tab" @tab-change="load">
      <el-tab-pane label="代理与提现" name="agents">
        <h3>代理资料</h3><el-table :data="agents"><el-table-column prop="username" label="用户"/><el-table-column prop="tier_code" label="等级"/><el-table-column prop="status" label="状态"/><el-table-column prop="customer_count" label="客户"/><el-table-column label="操作" min-width="260"><template #default="scope"><el-button size="small" type="success" @click="review(scope.row.id,'ACTIVE')">通过</el-button><el-button size="small" @click="review(scope.row.id,'SUSPENDED')">暂停</el-button><el-button size="small" type="danger" @click="review(scope.row.id,'REJECTED')">拒绝</el-button></template></el-table-column></el-table>
        <h3>提现审核</h3><el-table :data="withdrawals"><el-table-column prop="request_no" label="请求号" min-width="180"/><el-table-column prop="username" label="代理"/><el-table-column prop="amount" label="金额（账务单位）"/><el-table-column prop="destination_type" label="方式"/><el-table-column prop="status" label="状态"/><el-table-column label="操作" min-width="240"><template #default="scope"><el-button size="small" type="success" @click="reviewWithdrawal(scope.row.id,'APPROVED')">批准</el-button><el-button size="small" @click="reviewWithdrawal(scope.row.id,'PAID')">已付款</el-button><el-button size="small" type="danger" @click="reviewWithdrawal(scope.row.id,'REJECTED')">驳回</el-button></template></el-table-column></el-table>
        <h3>服务订单成本</h3><el-table :data="serviceCosts"><el-table-column prop="name" label="服务"/><el-table-column label="单位成本（分）" min-width="170"><template #default="scope"><el-input-number v-model="scope.row.cost_cents" :min="0"/></template></el-table-column><el-table-column label="退款观察期（天）" min-width="180"><template #default="scope"><el-input-number v-model="scope.row.commission_refund_window_days" :min="0" :max="365"/></template></el-table-column><el-table-column label="操作"><template #default="scope"><el-button size="small" @click="saveServiceCost(scope.row)">保存</el-button></template></el-table-column></el-table>
      </el-tab-pane>
      <el-tab-pane label="上游账号" name="accounts"><el-alert v-if="accountStatus && !accountStatus.enabled" type="warning" :closable="false" title="新账号调度功能开关当前关闭"/><el-table :data="accounts"><el-table-column prop="id" label="ID" width="70"/><el-table-column prop="name" label="账号"/><el-table-column prop="platform" label="平台"/><el-table-column prop="auth_type" label="认证"/><el-table-column prop="account_group" label="分组"/><el-table-column prop="health_status" label="健康"/><el-table-column prop="cost_reliable" label="成本可靠"><template #default="scope">{{ scope.row.cost_reliable?'是':'否' }}</template></el-table-column><el-table-column label="操作" min-width="160"><template #default="scope"><el-button size="small" @click="testAccount(scope.row.id)">测试</el-button><el-button size="small" @click="pause(scope.row.id,scope.row.enabled)">{{ scope.row.enabled?'暂停':'恢复' }}</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="出站代理" name="proxies"><el-table :data="proxies"><el-table-column prop="name" label="名称"/><el-table-column prop="protocol" label="协议"/><el-table-column prop="host" label="主机"/><el-table-column prop="health_status" label="健康"/><el-table-column prop="latency_ms" label="延迟 ms"/><el-table-column label="操作"><template #default="scope"><el-button size="small" @click="testProxy(scope.row.id)">探测</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="实时运维" name="ops"><div class="ops-grid"><article v-for="(value,key) in opsCards" :key="key"><span>{{ key }}</span><strong>{{ value }}</strong></article></div><el-table :data="ops.heartbeats||[]"><el-table-column prop="task_key" label="任务"/><el-table-column prop="status" label="状态"/><el-table-column prop="updated_at" label="心跳"/></el-table></el-tab-pane>
      <el-tab-pane label="公告与备份" name="platform"><div class="platform-actions"><el-input v-model="announcement.title" placeholder="公告标题"/><el-input v-model="announcement.content" type="textarea" placeholder="公告内容"/><el-button type="primary" @click="createAnnouncement">发布公告</el-button><el-button @click="requestBackup">登记手工备份</el-button></div><h3>备份记录</h3><el-table :data="backups"><el-table-column prop="request_no" label="请求号"/><el-table-column prop="status" label="状态"/><el-table-column prop="created_at" label="创建时间"/></el-table></el-tab-pane>
    </el-tabs>
  </section>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import http,{getHttpErrorMessage} from '@/utils/http'
const tab=ref('agents'),agents=ref<any[]>([]),withdrawals=ref<any[]>([]),serviceCosts=ref<any[]>([]),accounts=ref<any[]>([]),proxies=ref<any[]>([]),backups=ref<any[]>([]),ops=reactive<any>({}),accountStatus=ref<any>(null),announcement=reactive({title:'',content:'',audience:'ALL'})
const opsCards=computed(()=>({QPS:ops.qps||0,TPS:ops.tps||0,'P95':`${ops.p95Ms||0} ms`,'成功率':`${(Number(ops.successRate||0)*100).toFixed(2)}%`,'活跃账号':ops.activeAccounts||0,'开放告警':ops.openAlerts||0}))
async function load(){try{if(tab.value==='agents'){const [a,w,s]=await Promise.all([http.get('/api/admin/api/agents'),http.get('/api/admin/api/agents/withdrawals'),http.get('/api/admin/api/agents/service-costs')]);agents.value=a.data||[];withdrawals.value=w.data||[];serviceCosts.value=s.data||[]}if(tab.value==='accounts'){const [a,s]=await Promise.all([http.get('/api/admin/api/provider-accounts'),http.get('/api/admin/api/provider-accounts/status')]);accounts.value=a.data||[];accountStatus.value=s.data}if(tab.value==='proxies')proxies.value=(await http.get('/api/admin/api/upstream-proxies')).data||[];if(tab.value==='ops')Object.assign(ops,(await http.get('/api/admin/api/operations/overview')).data||{});if(tab.value==='platform')backups.value=(await http.get('/api/admin/api/backups')).data||[]}catch(e){ElMessage.error(getHttpErrorMessage(e,'数据加载失败'))}}
async function review(id:number,status:string){await http.post(`/api/admin/api/agents/${id}/review`,{status,tierCode:'BASIC'});await load()}
async function reviewWithdrawal(id:number,status:string){try{await http.post(`/api/admin/api/agents/withdrawals/${id}/review`,{status,note:'后台人工审核'});ElMessage.success('提现状态已更新');await load()}catch(e){ElMessage.error(getHttpErrorMessage(e,'提现审核失败'))}}
async function saveServiceCost(row:any){try{await http.put(`/api/admin/api/agents/service-costs/${row.id}`,{costCents:row.cost_cents,refundWindowDays:row.commission_refund_window_days});ElMessage.success('服务成本已保存')}catch(e){ElMessage.error(getHttpErrorMessage(e,'服务成本保存失败'))}}
async function pause(id:number,enabled:boolean){await http.post(`/api/admin/api/provider-accounts/${id}/${enabled?'pause':'resume'}`);await load()}
async function testAccount(id:number){try{const res=await http.post(`/api/admin/api/provider-accounts/${id}/test`);ElMessage.success(res.data?.message||'账号测试完成');await load()}catch(e){ElMessage.error(getHttpErrorMessage(e,'账号测试失败'))}}
async function testProxy(id:number){await http.post(`/api/admin/api/upstream-proxies/${id}/test`);await load()}
async function createAnnouncement(){try{await http.post('/api/admin/api/announcements',announcement);ElMessage.success('公告已发布');announcement.title='';announcement.content=''}catch(e){ElMessage.error(getHttpErrorMessage(e,'公告发布失败'))}}
async function requestBackup(){try{await http.post('/api/admin/api/backups');ElMessage.success('备份请求已登记');await load()}catch(e){ElMessage.error(getHttpErrorMessage(e,'备份登记失败'))}}
onMounted(load)
</script>

<style scoped>
.admin-evolution{min-width:0;padding:22px;border:1px solid #d7e4f7;border-radius:12px;background:#fff}.ops-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-bottom:18px}.ops-grid article{padding:18px;border-radius:10px;background:#f3f8ff}.ops-grid span,.ops-grid strong{display:block}.ops-grid span{color:#647792}.ops-grid strong{margin-top:6px;font-size:24px}.platform-actions{display:grid;max-width:720px;gap:12px;margin-bottom:26px}@media(max-width:760px){.ops-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.admin-evolution{padding:12px;overflow-x:auto;-webkit-overflow-scrolling:touch}}
</style>
