<template>
  <section class="admin-evolution">
    <el-tabs v-model="tab" @tab-change="load">
      <el-tab-pane label="代理与提现" name="agents">
        <h3>代理资料</h3><el-table :data="agents"><el-table-column prop="username" label="用户"/><el-table-column prop="tier_code" label="等级"/><el-table-column prop="status" label="状态"/><el-table-column prop="customer_count" label="客户"/><el-table-column label="操作" min-width="260"><template #default="scope"><el-button size="small" type="success" @click="review(scope.row.id,'ACTIVE')">通过</el-button><el-button size="small" @click="review(scope.row.id,'SUSPENDED')">暂停</el-button><el-button size="small" type="danger" @click="review(scope.row.id,'REJECTED')">拒绝</el-button></template></el-table-column></el-table>
        <h3>提现审核</h3><el-table :data="withdrawals"><el-table-column prop="request_no" label="请求号" min-width="180"/><el-table-column prop="username" label="代理"/><el-table-column prop="amount" label="金额（账务单位）"/><el-table-column prop="destination_type" label="方式"/><el-table-column prop="status" label="状态"/><el-table-column label="操作" min-width="240"><template #default="scope"><el-button size="small" type="success" @click="reviewWithdrawal(scope.row.id,'APPROVED')">批准</el-button><el-button size="small" @click="reviewWithdrawal(scope.row.id,'PAID')">已付款</el-button><el-button size="small" type="danger" @click="reviewWithdrawal(scope.row.id,'REJECTED')">驳回</el-button></template></el-table-column></el-table>
        <h3>服务订单成本</h3><el-table :data="serviceCosts"><el-table-column prop="name" label="服务"/><el-table-column label="单位成本（分）" min-width="170"><template #default="scope"><el-input-number v-model="scope.row.cost_cents" :min="0"/></template></el-table-column><el-table-column label="退款观察期（天）" min-width="180"><template #default="scope"><el-input-number v-model="scope.row.commission_refund_window_days" :min="0" :max="365"/></template></el-table-column><el-table-column label="操作"><template #default="scope"><el-button size="small" @click="saveServiceCost(scope.row)">保存</el-button></template></el-table-column></el-table>
      </el-tab-pane>
      <el-tab-pane label="上游账号" name="accounts">
        <el-alert v-if="accountStatus && (!accountStatus.enabled||!accountStatus.oauthEnabled)" type="warning" :closable="false" title="账号池或 OAuth 总开关未启用；当前保持 fail-closed"/>
        <el-alert v-if="oauthClients.length&&!oauthClients[0]?.encryptionReady" type="error" :closable="false" title="后端未注入 DATA_ENCRYPTION_KEY，为防止明文落库，OAuth Client 配置已禁止保存"/>
        <div class="account-actions"><el-button type="primary" @click="openAuthorize">授权订阅账号</el-button><el-button @click="selectOAuthClient(oauthClientForm.platform)">OAuth Client 配置</el-button><el-button @click="priceDialog=true">新建价格模板</el-button><el-button @click="manualDialog=true">粘贴回调 URL</el-button></div>
        <div class="platform-status"><el-tag v-for="(value,key) in accountStatus?.oauthPlatforms||{}" :key="key" :type="value.ready?'success':'info'">{{ key }}：{{ value.ready?'就绪':value.enabled?'缺配置':'关闭' }}</el-tag></div>
        <el-table :data="oauthClients" size="small" class="oauth-client-table"><el-table-column prop="platform" label="OAuth 平台" width="120"/><el-table-column prop="source" label="配置来源" width="150"/><el-table-column prop="clientIdPreview" label="Client ID" min-width="150"/><el-table-column label="Secret" width="90"><template #default="scope">{{ scope.row.hasClientSecret?'已设置':'无' }}</template></el-table-column><el-table-column label="状态" width="110"><template #default="scope"><el-tag :type="scope.row.enabled&&scope.row.configured?'success':'info'">{{ scope.row.enabled?(scope.row.configured?'已启用':'不完整'):'已禁用' }}</el-tag></template></el-table-column><el-table-column prop="lastTestStatus" label="端点检查" width="110"/><el-table-column label="操作" width="180"><template #default="scope"><el-button size="small" @click="editOAuthClient(scope.row)">编辑</el-button><el-button size="small" @click="testOAuthClient(scope.row.platform)">检查</el-button></template></el-table-column></el-table>
        <el-table :data="accounts"><el-table-column prop="id" label="ID" width="70"/><el-table-column prop="name" label="账号" min-width="150"/><el-table-column prop="platform" label="平台"/><el-table-column prop="email_preview" label="邮箱" min-width="150"/><el-table-column prop="subscription_tier" label="订阅"/><el-table-column prop="entitlement_status" label="权益"/><el-table-column prop="oauth_expires_at" label="Token 到期" min-width="170"/><el-table-column prop="account_group" label="分组"/><el-table-column prop="health_status" label="健康"/><el-table-column prop="cost_reliable" label="可靠成本"><template #default="scope">{{ scope.row.cost_reliable?'是':'否' }}</template></el-table-column><el-table-column label="操作" min-width="390"><template #default="scope"><el-button size="small" @click="testAccount(scope.row.id)">测试</el-button><el-button v-if="scope.row.auth_type==='OAUTH'" size="small" @click="refreshAccount(scope.row.id)">刷新</el-button><el-button v-if="scope.row.auth_type==='OAUTH'" size="small" @click="syncAccount(scope.row.id)">同步</el-button><el-button v-if="scope.row.auth_type==='OAUTH'" size="small" @click="reauthorize(scope.row)">重授权</el-button><el-button size="small" @click="pause(scope.row.id,scope.row.enabled)">{{ scope.row.enabled?'暂停':'恢复' }}</el-button></template></el-table-column></el-table>
        <h3>价格模板</h3><el-table :data="priceTemplates"><el-table-column prop="name" label="模板"/><el-table-column prop="platform" label="平台"/><el-table-column prop="model_pattern" label="模型规则"/><el-table-column prop="pricing_unit" label="单位"/><el-table-column prop="source_url" label="来源" min-width="180"/><el-table-column label="操作"><template #default="scope"><el-button type="danger" link @click="deletePrice(scope.row.id)">删除</el-button></template></el-table-column></el-table>
        <el-dialog v-model="authorizeDialog" title="授权上游订阅账号" width="560px"><el-form label-width="110px"><el-form-item label="平台"><el-select v-model="authorization.platform" style="width:100%"><el-option v-for="p in oauthPlatforms" :key="p" :label="p" :value="p" :disabled="!accountStatus?.oauthPlatforms?.[p]?.ready"/></el-select></el-form-item><el-form-item label="价格模板"><el-select v-model="authorization.priceTemplateId" style="width:100%"><el-option v-for="p in matchingTemplates" :key="p.id" :label="`${p.name} · ${p.model_pattern}`" :value="p.id"/></el-select></el-form-item><el-form-item label="出站代理"><el-select v-model="authorization.upstreamProxyId" clearable placeholder="直连" style="width:100%"><el-option v-for="p in proxies" :key="p.id" :label="`${p.name} · ${p.health_status}`" :value="p.id" :disabled="!p.enabled"/></el-select></el-form-item><el-form-item label="账号分组"><el-input v-model="authorization.accountGroup"/></el-form-item><el-form-item label="模型范围"><el-input v-model="authorization.modelScope" placeholder="* 或逗号分隔模型"/></el-form-item><el-form-item label="回调模式"><el-radio-group v-model="authorization.callbackMode"><el-radio value="POPUP">自动弹窗</el-radio><el-radio value="MANUAL">手工粘贴</el-radio></el-radio-group></el-form-item></el-form><template #footer><el-button @click="authorizeDialog=false">取消</el-button><el-button type="primary" @click="startAuthorize">开始授权</el-button></template></el-dialog>
        <el-dialog v-model="manualDialog" title="粘贴 OAuth 回调" width="600px"><el-select v-model="manual.platform" style="width:100%;margin-bottom:12px"><el-option v-for="p in oauthPlatforms" :key="p" :label="p" :value="p"/></el-select><el-input v-model="manual.callbackUrl" type="textarea" :rows="4" placeholder="粘贴浏览器最终回调 URL（包含 code 和 state）"/><template #footer><el-button @click="manualDialog=false">取消</el-button><el-button type="primary" @click="exchangeManual">完成授权</el-button></template></el-dialog>
        <el-dialog v-model="priceDialog" title="新建价格模板" width="620px"><el-form label-width="120px"><el-form-item label="名称"><el-input v-model="price.name"/></el-form-item><el-form-item label="平台"><el-select v-model="price.platform"><el-option v-for="p in oauthPlatforms" :key="p" :label="p" :value="p"/></el-select></el-form-item><el-form-item label="模型规则"><el-input v-model="price.modelPattern" placeholder="精确名、gpt-* 或 *"/></el-form-item><el-form-item label="官网输入/输出"><el-input-number v-model="price.officialInput" :min="0"/><el-input-number v-model="price.officialOutput" :min="0"/></el-form-item><el-form-item label="成本输入/输出"><el-input-number v-model="price.costInput" :min="0"/><el-input-number v-model="price.costOutput" :min="0"/></el-form-item><el-form-item label="售价输入/输出"><el-input-number v-model="price.saleInput" :min="0"/><el-input-number v-model="price.saleOutput" :min="0"/></el-form-item><el-form-item label="来源 URL"><el-input v-model="price.sourceUrl"/></el-form-item></el-form><template #footer><el-button @click="priceDialog=false">取消</el-button><el-button type="primary" @click="createPrice">保存</el-button></template></el-dialog>
        <el-dialog v-model="oauthClientDialog" title="OAuth Client 安全配置" width="760px" destroy-on-close>
          <el-alert type="warning" :closable="false" title="Client Secret 写入后不会再显示；留空表示保留原值。禁用会立即停止新授权和 Token 刷新；修改 Client/端点后旧账号必须重新授权。"/>
          <el-form label-width="150px" class="oauth-client-form">
            <el-form-item label="平台"><el-select v-model="oauthClientForm.platform" style="width:100%" @change="selectOAuthClient"><el-option v-for="p in oauthPlatforms" :key="p" :label="p" :value="p"/></el-select></el-form-item>
            <el-form-item label="启用"><el-switch v-model="oauthClientForm.enabled"/></el-form-item>
            <el-form-item label="回调根地址"><el-input v-model="oauthClientForm.callbackBaseUrl" placeholder="https://api.example.com"/></el-form-item>
            <el-form-item label="Client ID"><el-input v-model="oauthClientForm.clientId" :placeholder="oauthClientForm.clientIdPreview?`已设置 ${oauthClientForm.clientIdPreview}；留空保留`:'请输入 Client ID'" autocomplete="off"/></el-form-item>
            <el-form-item label="Client Secret"><el-input v-model="oauthClientForm.clientSecret" type="password" show-password placeholder="留空保留原 Secret" autocomplete="new-password"/></el-form-item>
            <el-form-item v-if="oauthClientForm.hasClientSecret" label="清除 Secret"><el-checkbox v-model="oauthClientForm.clearClientSecret">确认将该 Client 改为无 Secret 的 PKCE Public Client</el-checkbox></el-form-item>
            <el-form-item label="Authorization URI"><el-input v-model="oauthClientForm.authorizationUri"/></el-form-item>
            <el-form-item label="Token URI"><el-input v-model="oauthClientForm.tokenUri"/></el-form-item>
            <el-form-item label="UserInfo URI"><el-input v-model="oauthClientForm.userinfoUri"/></el-form-item>
            <el-form-item label="Models URI"><el-input v-model="oauthClientForm.modelsUri"/></el-form-item>
            <el-form-item label="Probe URI"><el-input v-model="oauthClientForm.probeUri"/></el-form-item>
            <el-form-item label="推理 API 根地址"><el-input v-model="oauthClientForm.upstreamBaseUrl"/></el-form-item>
            <el-form-item label="Scopes"><el-input v-model="oauthClientForm.scopes" placeholder="openid profile email offline_access"/></el-form-item>
          </el-form>
          <template #footer><el-button @click="oauthClientDialog=false">取消</el-button><el-button :loading="oauthClientSaving" type="primary" @click="saveOAuthClient">加密保存</el-button></template>
        </el-dialog>
      </el-tab-pane>
      <el-tab-pane label="出站代理" name="proxies"><el-table :data="proxies"><el-table-column prop="name" label="名称"/><el-table-column prop="protocol" label="协议"/><el-table-column prop="host" label="主机"/><el-table-column prop="health_status" label="健康"/><el-table-column prop="latency_ms" label="延迟 ms"/><el-table-column label="操作"><template #default="scope"><el-button size="small" @click="testProxy(scope.row.id)">探测</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="实时运维" name="ops"><div class="ops-grid"><article v-for="(value,key) in opsCards" :key="key"><span>{{ key }}</span><strong>{{ value }}</strong></article></div><el-table :data="ops.heartbeats||[]"><el-table-column prop="task_key" label="任务"/><el-table-column prop="status" label="状态"/><el-table-column prop="updated_at" label="心跳"/></el-table></el-tab-pane>
      <el-tab-pane label="公告与备份" name="platform"><div class="platform-actions"><el-input v-model="announcement.title" placeholder="公告标题"/><el-input v-model="announcement.content" type="textarea" placeholder="公告内容"/><el-button type="primary" @click="createAnnouncement">发布公告</el-button><el-button @click="requestBackup">登记手工备份</el-button></div><h3>备份记录</h3><el-table :data="backups"><el-table-column prop="request_no" label="请求号"/><el-table-column prop="status" label="状态"/><el-table-column prop="created_at" label="创建时间"/></el-table></el-tab-pane>
    </el-tabs>
  </section>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import http,{getHttpErrorMessage} from '@/utils/http'
const tab=ref('agents'),agents=ref<any[]>([]),withdrawals=ref<any[]>([]),serviceCosts=ref<any[]>([]),accounts=ref<any[]>([]),proxies=ref<any[]>([]),backups=ref<any[]>([]),priceTemplates=ref<any[]>([]),oauthClients=ref<any[]>([]),ops=reactive<any>({}),accountStatus=ref<any>(null),announcement=reactive({title:'',content:'',audience:'ALL'})
const oauthPlatforms=['CODEX','CLAUDE','GEMINI','ANTIGRAVITY','GROK'],authorizeDialog=ref(false),manualDialog=ref(false),priceDialog=ref(false),oauthClientDialog=ref(false),oauthClientSaving=ref(false)
const oauthClientForm=reactive<any>({platform:'CODEX',enabled:false,version:0,clientIdPreview:'',hasClientSecret:false,callbackBaseUrl:'',clientId:'',clientSecret:'',clearClientSecret:false,authorizationUri:'',tokenUri:'',userinfoUri:'',modelsUri:'',probeUri:'',upstreamBaseUrl:'',scopes:''})
const authorization=reactive<any>({platform:'CODEX',priceTemplateId:null,upstreamProxyId:null,accountGroup:'default',modelScope:'*',callbackMode:'POPUP'}),manual=reactive({platform:'CODEX',callbackUrl:''}),price=reactive<any>({name:'',platform:'CODEX',modelPattern:'*',officialInput:0,officialOutput:0,costInput:0,costOutput:0,saleInput:0,saleOutput:0,sourceUrl:''})
const matchingTemplates=computed(()=>priceTemplates.value.filter(item=>item.platform===authorization.platform&&item.enabled))
const opsCards=computed(()=>({QPS:ops.qps||0,TPS:ops.tps||0,'P95':`${ops.p95Ms||0} ms`,'成功率':`${(Number(ops.successRate||0)*100).toFixed(2)}%`,'活跃账号':ops.activeAccounts||0,'开放告警':ops.openAlerts||0}))
async function load(){try{if(tab.value==='agents'){const [a,w,s]=await Promise.all([http.get('/api/admin/api/agents'),http.get('/api/admin/api/agents/withdrawals'),http.get('/api/admin/api/agents/service-costs')]);agents.value=a.data||[];withdrawals.value=w.data||[];serviceCosts.value=s.data||[]}if(tab.value==='accounts'){const [a,s,p,x,c]=await Promise.all([http.get('/api/admin/api/provider-accounts'),http.get('/api/admin/api/provider-accounts/status'),http.get('/api/admin/api/provider-price-templates'),http.get('/api/admin/api/upstream-proxies'),http.get('/api/admin/api/provider-oauth-clients')]);accounts.value=a.data||[];accountStatus.value=s.data;priceTemplates.value=p.data||[];proxies.value=x.data||[];oauthClients.value=c.data||[]}if(tab.value==='proxies')proxies.value=(await http.get('/api/admin/api/upstream-proxies')).data||[];if(tab.value==='ops')Object.assign(ops,(await http.get('/api/admin/api/operations/overview')).data||{});if(tab.value==='platform')backups.value=(await http.get('/api/admin/api/backups')).data||[]}catch(e){ElMessage.error(getHttpErrorMessage(e,'数据加载失败'))}}
function editOAuthClient(row:any){Object.assign(oauthClientForm,{platform:row.platform,enabled:!!row.enabled,version:Number(row.version||0),clientIdPreview:row.clientIdPreview||'',hasClientSecret:!!row.hasClientSecret,callbackBaseUrl:row.callbackBaseUrl||'',clientId:'',clientSecret:'',clearClientSecret:false,authorizationUri:row.authorizationUri||'',tokenUri:row.tokenUri||'',userinfoUri:row.userinfoUri||'',modelsUri:row.modelsUri||'',probeUri:row.probeUri||'',upstreamBaseUrl:row.upstreamBaseUrl||'',scopes:row.scopes||''});oauthClientDialog.value=true}
function selectOAuthClient(platform:string){const row=oauthClients.value.find(item=>item.platform===platform)||{platform};editOAuthClient(row)}
async function saveOAuthClient(){oauthClientSaving.value=true;try{await http.put(`/api/admin/api/provider-oauth-clients/${oauthClientForm.platform}`,oauthClientForm);ElMessage.success('OAuth Client 配置已加密保存');oauthClientForm.clientSecret='';oauthClientDialog.value=false;await load()}catch(e){ElMessage.error(getHttpErrorMessage(e,'OAuth Client 配置保存失败'))}finally{oauthClientSaving.value=false}}
async function testOAuthClient(platform:string){try{const res=await http.post(`/api/admin/api/provider-oauth-clients/${platform}/test`);if(res.data?.status==='REACHABLE')ElMessage.success('所有端点可达');else ElMessage.warning('部分端点不可达');await load()}catch(e){ElMessage.error(getHttpErrorMessage(e,'OAuth 端点检查失败'))}}
async function review(id:number,status:string){await http.post(`/api/admin/api/agents/${id}/review`,{status,tierCode:'BASIC'});await load()}
async function reviewWithdrawal(id:number,status:string){try{await http.post(`/api/admin/api/agents/withdrawals/${id}/review`,{status,note:'后台人工审核'});ElMessage.success('提现状态已更新');await load()}catch(e){ElMessage.error(getHttpErrorMessage(e,'提现审核失败'))}}
async function saveServiceCost(row:any){try{await http.put(`/api/admin/api/agents/service-costs/${row.id}`,{costCents:row.cost_cents,refundWindowDays:row.commission_refund_window_days});ElMessage.success('服务成本已保存')}catch(e){ElMessage.error(getHttpErrorMessage(e,'服务成本保存失败'))}}
async function pause(id:number,enabled:boolean){await http.post(`/api/admin/api/provider-accounts/${id}/${enabled?'pause':'resume'}`);await load()}
async function testAccount(id:number){try{const res=await http.post(`/api/admin/api/provider-accounts/${id}/test`);ElMessage.success(res.data?.message||'账号测试完成');await load()}catch(e){ElMessage.error(getHttpErrorMessage(e,'账号测试失败'))}}
async function refreshAccount(id:number){try{await http.post(`/api/admin/api/provider-accounts/${id}/refresh`);ElMessage.success('Token 已刷新');await load()}catch(e){ElMessage.error(getHttpErrorMessage(e,'Token 刷新失败'))}}
async function syncAccount(id:number){try{await Promise.all([http.post(`/api/admin/api/provider-accounts/${id}/sync-models`),http.post(`/api/admin/api/provider-accounts/${id}/sync-quota`)]);ElMessage.success('模型与额度已同步');await load()}catch(e){ElMessage.error(getHttpErrorMessage(e,'账号同步失败'))}}
async function reauthorize(row:any){try{const res=await http.post(`/api/admin/api/provider-accounts/${row.id}/reauthorize`,{callbackMode:'POPUP'});window.open(res.data.authorizationUrl,'linknux-oauth','width=620,height=760')}catch(e){ElMessage.error(getHttpErrorMessage(e,'无法启动重新授权'))}}
function openAuthorize(){authorizeDialog.value=true;if(!authorization.priceTemplateId)authorization.priceTemplateId=matchingTemplates.value[0]?.id||null}
async function startAuthorize(){try{const res=await http.post(`/api/admin/api/provider-accounts/oauth/${authorization.platform}/authorize`,authorization);authorizeDialog.value=false;if(authorization.callbackMode==='POPUP')window.open(res.data.authorizationUrl,'linknux-oauth','width=620,height=760');else{manual.platform=authorization.platform;manualDialog.value=true;window.open(res.data.authorizationUrl,'_blank')}}catch(e){ElMessage.error(getHttpErrorMessage(e,'无法启动授权'))}}
async function exchangeManual(){try{await http.post(`/api/admin/api/provider-accounts/oauth/${manual.platform}/exchange`,{callbackUrl:manual.callbackUrl});manualDialog.value=false;manual.callbackUrl='';ElMessage.success('授权成功');await load()}catch(e){ElMessage.error(getHttpErrorMessage(e,'回调交换失败'))}}
async function createPrice(){try{await http.post('/api/admin/api/provider-price-templates',{name:price.name,platform:price.platform,modelPattern:price.modelPattern,pricingUnit:'TOKEN',officialPrice:{inputPerMillion:price.officialInput,outputPerMillion:price.officialOutput},costPrice:{inputPerMillion:price.costInput,outputPerMillion:price.costOutput},salePrice:{inputPerMillion:price.saleInput,outputPerMillion:price.saleOutput},sourceUrl:price.sourceUrl});priceDialog.value=false;ElMessage.success('价格模板已创建');await load()}catch(e){ElMessage.error(getHttpErrorMessage(e,'价格模板创建失败'))}}
async function deletePrice(id:number){try{await http.delete(`/api/admin/api/provider-price-templates/${id}`);await load()}catch(e){ElMessage.error(getHttpErrorMessage(e,'价格模板删除失败'))}}
function oauthMessage(event:MessageEvent){if(event.origin===location.origin&&event.data?.type==='linknux-upstream-oauth'){ElMessage.success('上游账号授权完成');load()}}
async function testProxy(id:number){await http.post(`/api/admin/api/upstream-proxies/${id}/test`);await load()}
async function createAnnouncement(){try{await http.post('/api/admin/api/announcements',announcement);ElMessage.success('公告已发布');announcement.title='';announcement.content=''}catch(e){ElMessage.error(getHttpErrorMessage(e,'公告发布失败'))}}
async function requestBackup(){try{await http.post('/api/admin/api/backups');ElMessage.success('备份请求已登记');await load()}catch(e){ElMessage.error(getHttpErrorMessage(e,'备份登记失败'))}}
onMounted(()=>{window.addEventListener('message',oauthMessage);load()})
onUnmounted(()=>window.removeEventListener('message',oauthMessage))
</script>

<style scoped>
.admin-evolution{min-width:0;padding:22px;border:1px solid #d7e4f7;border-radius:12px;background:#fff}.account-actions{display:flex;flex-wrap:wrap;gap:10px;margin:14px 0}.platform-status{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:14px}.oauth-client-table{margin-bottom:18px}.oauth-client-form{margin-top:18px}.ops-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-bottom:18px}.ops-grid article{padding:18px;border-radius:10px;background:#f3f8ff}.ops-grid span,.ops-grid strong{display:block}.ops-grid span{color:#647792}.ops-grid strong{margin-top:6px;font-size:24px}.platform-actions{display:grid;max-width:720px;gap:12px;margin-bottom:26px}@media(max-width:760px){.ops-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.admin-evolution{padding:12px;overflow-x:auto;-webkit-overflow-scrolling:touch}}
</style>
