<template>
 <div class="gateway-workbench">
  <header class="heading"><div><p>上游站点 → 分组 → 模型，统一管理同步、定价与发布。</p></div><div class="actions"><NewApiConnect @connected="reloadAll"/><el-button :loading="loading" @click="load">刷新</el-button></div></header>
  <div class="actions"><el-button v-for="metric in metrics" :key="metric.key" text @click="showMetric(metric.state)">{{metric.label}} {{summary[metric.key] ?? 0}}</el-button></div>
  <section class="filters">
   <el-select v-model="siteId" clearable filterable remote :remote-method="searchSites" placeholder="全部上游" @change="siteChanged"><el-option v-for="s in siteOptions" :key="s.id" :value="s.id" :label="s.name"/><template #footer><el-button v-if="siteOptions.length<siteTotal" link @click="searchSites(siteQuery,true)">加载更多</el-button></template></el-select>
   <el-select v-model="groupId" clearable filterable remote :remote-method="searchGroups" placeholder="全部上游分组" @change="filterChanged"><el-option v-for="g in groupOptions" :key="g.id" :value="g.id" :label="g.group_name"/><template #footer><el-button v-if="groupOptions.length<groupTotal" link @click="searchGroups(groupQuery,true)">加载更多</el-button></template></el-select>
   <el-input v-model="query" clearable placeholder="搜索名称" @keyup.enter="filterChanged" @clear="filterChanged"/>
   <el-button type="primary" :loading="working" @click="synchronize()">同步目录</el-button>
   <el-button v-if="siteOptions.find(s=>s.id===siteId)?.adapter==='aiapibank'" :loading="working" @click="syncGroups(siteId)">同步上游分组</el-button>
   <el-button v-if="siteId" @click="editSite">站点设置</el-button>
   <el-button @click="pricingEditor?.show()">销售加价设置</el-button>
  </section>
  <el-tabs v-model="tab" @tab-change="tabChanged"><el-tab-pane label="上游与分组" name="channels"/><el-tab-pane label="模型与定价" name="models"/><el-tab-pane label="运行记录" name="records"/></el-tabs>
  <el-alert v-if="error" :title="error" type="error" :closable="false"/>
  <section class="panel">
   <div class="actions" v-if="tab === 'models'"><el-select v-model="modelState" clearable placeholder="全部模型状态" @change="filterChanged"><el-option label="待导入" value="pending-import"/><el-option label="待定价" value="pending-price"/><el-option label="待发布" value="pending-publish"/><el-option label="已发布" value="published"/><el-option label="已停用" value="disabled"/></el-select><el-button :disabled="!selected.length || working" type="primary" @click="publish">{{modelState==='pending-import'?'导入所选模型':'自动处理并发布'}}</el-button><span>已选 {{ selected.length }} 个（当前页）</span></div>
   <p v-if="tab==='models' && modelState!=='pending-import'">发布会自动同步报价、应用已保存的加价规则并校验可用性；暂未满足条件的每15分钟重试，可随时取消。</p>
   <PagedTable scrollbar-always-on v-if="tab === 'channels'" :data="rows" v-loading="loading" list-id="ModelGateway-1" pagination="external">
    <el-table-column prop="site_name" label="上游" min-width="120"/><el-table-column prop="group_name" label="上游分组" min-width="170"/>
    <el-table-column prop="model_count" label="模型" width="80"/><el-table-column label="前台名称" min-width="160"><template #default="{row}">{{row.public_name}} <el-button link type="primary" @click="editPublicName(row)">修改</el-button></template></el-table-column>
    <el-table-column label="凭据 / 启用" width="130"><template #default="{row}"><el-tag :type="row.credential_configured?'success':'warning'">{{row.credential_configured?'Key 已配置':'缺少 Key'}}</el-tag><div>{{row.enabled?'已启用':'未启用'}}</div></template></el-table-column>
    <el-table-column label="测试健康" min-width="120"><template #default="{row}"><el-tag :type="row.health_status==='HEALTHY'?'success':row.health_status==='UNTESTED'?'info':'warning'">{{healthLabel(row.health_status)}}</el-tag></template></el-table-column>
    <el-table-column label="同步" min-width="130"><template #default="{row}"><el-tag :type="statusType(row.sync_status,row.sync_enabled)">{{statusLabel(row.sync_status)}}</el-tag><small v-if="!row.sync_enabled">自动同步已暂停</small></template></el-table-column>
    <el-table-column label="最近结果 / 原因" min-width="240"><template #default="{row}"><span :class="{'failure-text':row.sync_status==='ERROR'}">{{row.message || (row.sync_status==='ERROR'?'历史原因未记录':'尚未同步')}}</span><el-button v-if="row.message" link @click="detail=row">详情</el-button></template></el-table-column>
    <el-table-column label="操作" min-width="185" fixed="right"><template #default="{row}"><el-button link type="primary" @click="editGroup(row)">设置</el-button><el-button link type="primary" @click="synchronize(row.id)">同步</el-button><el-button link @click="test(row)">测试</el-button></template></el-table-column>
   </PagedTable>
   <PagedTable scrollbar-always-on v-else-if="tab === 'models'" :data="rows" v-loading="loading" @selection-change="selected=$event" list-id="ModelGateway-2" pagination="external">
    <el-table-column type="selection" width="42"/><el-table-column prop="public_model_name" label="模型 / 路由" min-width="210"/><el-table-column prop="site_name" label="上游" min-width="115"/><el-table-column prop="group_name" label="上游分组" min-width="175"/>
    <el-table-column label="采购 → 销售 (USD)" min-width="205"><template #default="{row}"><template v-if="row.pricing_unit==='TOKEN'">输入 {{row.input_cost_per_million??'未知'}} → {{row.input_price_per_million??'未知'}}<br/>输出 {{row.output_cost_per_million??'未知'}} → {{row.output_price_per_million??'未知'}}<small> / 百万 Token</small></template><template v-else>{{row.cost_unit_price??'未知'}} → {{row.sale_unit_price??'未知'}} / {{row.pricing_unit}}</template></template></el-table-column>
    <el-table-column label="状态" min-width="125"><template #default="{row}"><el-tag :type="row.enabled?'success':row.pricing_status==='VERIFIED'?'info':'warning'">{{row.enabled?'已发布':row.pricing_status==='VERIFIED'?'待发布':String(row.pricing_message||'').startsWith('已读取上游当前分层报价')?'分层价待配置':'待定价'}}</el-tag></template></el-table-column>
    <el-table-column prop="pricing_message" label="上游价格说明" min-width="310"><template #default="{row}">{{row.pricing_message||'尚未读取上游报价'}}</template></el-table-column>
    <el-table-column label="自动发布" min-width="260"><template #default="{row}"><template v-if="row.publication_status==='WAITING'"><el-tag type="warning">等待自动处理</el-tag><p>{{row.publication_reason||'等待同步报价'}}</p><small>下次尝试：{{row.publication_next_attempt_at}}</small><el-button link @click="cancelPublication(row.id)">取消自动发布</el-button></template><span v-else>{{row.publication_status==='PUBLISHED'?'自动处理完成':row.publication_status==='CANCELLED'?'已取消':'—'}}</span></template></el-table-column>
    <el-table-column label="销售规则" min-width="130"><template #default="{row}">{{row.manual_price?'手工价保护':'继承加价规则'}}<el-button v-if="row.id" link type="primary" @click="pricingEditor?.show(row.id)">加价规则</el-button><el-button v-if="row.id" link @click="modelEditor?.show(row.id)">编辑</el-button></template></el-table-column>
   </PagedTable>
   <template v-else><el-radio-group v-model="recordKind" @change="filterChanged"><el-radio-button value="jobs">目录同步</el-radio-button><el-radio-button value="tests">健康与测试</el-radio-button></el-radio-group><PagedTable scrollbar-always-on :data="rows" v-loading="loading" list-id="ModelGateway-3" pagination="external"><el-table-column prop="site_name" label="上游" min-width="110"/><el-table-column prop="group_name" label="分组" min-width="180"/><el-table-column label="状态" width="125"><template #default="{row}"><el-tag :type="statusType(row.status,true)">{{statusLabel(row.status)}}</el-tag></template></el-table-column><el-table-column label="结果 / 原因" min-width="230"><template #default="{row}"><span :class="{'failure-text':row.status==='ERROR'}">{{row.message||'等待执行'}}</span></template></el-table-column><el-table-column prop="created_at" label="开始时间" min-width="160"/><el-table-column label="操作" width="145" fixed="right"><template #default="{row}"><el-button link @click="detail=row">详情</el-button><el-button link type="primary" @click="row.job_type==='GROUPS'?syncGroups(row.site_id):synchronize(row.channel_id)">重试</el-button></template></el-table-column></PagedTable></template>
   <ListPagination v-model:page="paging.page" v-model:size="paging.size" v-model:all="paging.all" :total="paging.total" @change="load"/>
  </section>
  <el-dialog :model-value="!!detail" title="执行详情" width="min(640px,95vw)" @close="detail=null"><template v-if="detail"><p>状态：{{statusLabel(detail.status||detail.sync_status)}}</p><p>阶段：{{phaseLabel(detail.phase)}}</p><p>原因：{{detail.message||'历史原因未记录'}}</p><p v-if="detail.http_status">HTTP：{{detail.http_status}}</p><p>处理建议：{{detail.suggestion||'检查分组设置后重新同步'}}</p><p>时间：{{detail.finished_at||detail.created_at||'历史时间未记录'}}</p></template></el-dialog>
   <el-dialog v-model="settingsOpen" :title="settingsKind==='site'?'站点设置':'分组设置'" width="min(570px,95vw)" @closed="clearSettingsSecrets">
    <el-form label-position="top"><template v-if="settingsKind==='site' && siteOptions.find(s=>s.id===settingsId)?.adapter==='aiapibank'"><el-alert :type="accountAuth.status==='READY'?'success':accountAuth.status==='ERROR'?'error':'info'" :title="accountStatusMessage()" :closable="false"/><p>授权后同步账号可见目录，包括已获权限的“对接专用”分组；未授权时同步匿名模型广场。</p><template v-if="accountAuth.status!=='TWO_FACTOR_REQUIRED'"><el-form-item label="AiAPIBank 登录邮箱"><el-input v-model="accountAuth.email" maxlength="190" autocomplete="username"/></el-form-item><el-form-item label="AiAPIBank 登录密码（仅用于本次登录，不保存）"><el-input v-model="accountAuth.password" type="password" show-password maxlength="4096" autocomplete="current-password"/></el-form-item></template><el-form-item v-else label="6位两步验证码"><el-input v-model="accountAuth.totpCode" maxlength="6" inputmode="numeric" autocomplete="one-time-code"/></el-form-item><div class="actions"><el-button type="primary" :loading="working" @click="authorizeAiApiBank">{{accountAuth.status==='TWO_FACTOR_REQUIRED'?'验证并同步专用分组':'登录授权并同步'}}</el-button><el-button v-if="accountAuth.authenticated||accountAuth.status==='TWO_FACTOR_REQUIRED'" :disabled="working" @click="clearAiApiBankAuthorization">移除账号授权</el-button></div></template><el-form-item label="名称"><el-input v-model="settings.name" maxlength="120"/></el-form-item><template v-if="settingsKind==='group'"><el-form-item label="分组 Key（留空保留；AiAPIBank 保存后自动同步核验）"><el-input v-model="settings.apiKey" type="password" show-password autocomplete="off"/></el-form-item><el-form-item label="启用分组"><el-switch v-model="settings.enabled"/></el-form-item><el-form-item label="自动同步"><el-switch v-model="settings.syncEnabled"/></el-form-item><el-form-item label="前台名称继承站点"><el-switch v-model="settings.inheritDisplay"/></el-form-item></template><template v-if="settingsKind==='site'||!settings.inheritDisplay"><el-form-item label="前台公开名称"><el-input v-model="settings.publicName" maxlength="120"/></el-form-item><el-form-item label="公开代号（留空自动生成）"><el-input v-model="settings.publicCode"/></el-form-item><el-form-item label="徽标"><el-input v-model="settings.badgeText" maxlength="40"/><el-color-picker v-model="settings.badgeColor"/></el-form-item></template></el-form>
   <el-alert v-if="settingsError" type="error" :title="settingsError" :closable="false"/><template #footer><el-button type="primary" :loading="working" @click="saveSettings">保存</el-button></template>
  </el-dialog>
  <el-dialog v-model="batchOpen" title="批量处理结果"><PagedTable scrollbar-always-on :data="batchResults" list-id="ModelGateway-4"><el-table-column prop="id" label="模型 ID"/><el-table-column label="结果"><template #default="{row}"><el-tag :type="row.success?'success':row.queued?'warning':'danger'">{{row.success?'处理成功':row.queued?'已排队自动处理':'处理失败'}}</el-tag></template></el-table-column><el-table-column prop="reason" label="原因"/></PagedTable></el-dialog>
  <GatewayModelEditor ref="modelEditor" @changed="load"/><GatewayPricingEditor ref="pricingEditor" :site-id="siteId" :group-id="groupId" @changed="load"/>
 </div>
</template>
<script setup lang="ts">
import PagedTable from '@/components/PagedTable.vue'
import {ref,reactive,onMounted,onBeforeUnmount} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {ElMessage} from 'element-plus'
import http,{getHttpErrorMessage} from '../utils/http'
import {useListPage} from '../utils/listPage'
import ListPagination from '../components/ListPagination.vue'
import NewApiConnect from '../components/NewApiConnect.vue'
import GatewayPricingEditor from '../components/GatewayPricingEditor.vue'
import GatewayModelEditor from '../components/GatewayModelEditor.vue'
const route=useRoute(),router=useRouter()
const tab=ref(['models','catalog'].includes(String(route.query.tab))?'models':['health','records'].includes(String(route.query.tab))?'records':'channels')
const rows=ref<any[]>([]),siteOptions=ref<any[]>([]),groupOptions=ref<any[]>([]),siteId=ref<number>(),groupId=ref<number>(),query=ref(''),modelState=ref(''),selected=ref<any[]>([])
const modelEditor=ref<InstanceType<typeof GatewayModelEditor>>()
const summary=ref<Record<string,number>>({})
const metrics=[{key:'models',label:'模型总数',state:''},{key:'published',label:'已发布',state:'published'},{key:'pending_price',label:'待定价',state:'pending-price'},{key:'pending_publish',label:'待发布',state:'pending-publish'}]
function showMetric(state:string){tab.value='models';modelState.value=state;tabChanged()}
const recordKind=ref('jobs')
const loading=ref(false),working=ref(false),error=ref(''),detail=ref<any>(null),pricingEditor=ref<InstanceType<typeof GatewayPricingEditor>>()
const paging=useListPage('gateway-'+tab.value),settingsOpen=ref(false),settingsKind=ref('site'),settingsId=ref(0),settingsError=ref('')
const settings=reactive({name:'',enabled:false,syncEnabled:true,apiKey:'',publicName:'',publicCode:'',badgeText:'',badgeColor:'#2563eb',inheritDisplay:true})
const accountAuth=reactive({email:'',password:'',totpCode:'',emailPreview:'',authenticated:false,status:'ANONYMOUS',lastError:''})
const batchResults=ref<any[]>([]),batchOpen=ref(false)
async function cancelPublication(id:number){try{await http.delete(`/api/admin/api/gateway/models/${id}/publication`);await load()}catch(e){ElMessage.error(getHttpErrorMessage(e,'取消失败'))}}
const statusNames:Record<string,string>={ERROR:'失败',FAILED:'失败',SUCCESS:'成功',PARTIAL:'部分完成',QUEUED:'等待执行',RUNNING:'正在同步',PENDING:'未执行',IMPORTED:'已导入',MISSING_CONFIRMATION:'等待确认',GROUP_REMOVED:'分组已停用',DISABLED_MISSING:'上游分组已移除',CREDENTIAL_MISSING:'缺少凭据',UNMANAGED:'未接入同步',MISSING:'等待确认缺失'}
function phaseLabel(value:string){return ({GROUPS:'同步上游分组',MODELS:'读取模型目录',PRICING:'读取采购价格',APPLY:'应用目录与价格',CATALOG:'读取上游目录',TEST:'连通性测试'} as Record<string,string>)[value]||'历史阶段未记录'}
function statusLabel(value:string){return statusNames[value]||value||'未执行'}
function statusType(value:string,enabled:boolean):'danger'|'warning'|'success'|'info'{return ['ERROR','FAILED','GROUP_REMOVED','DISABLED_MISSING'].includes(value)?'danger':['PARTIAL','MISSING_CONFIRMATION','MISSING','CREDENTIAL_MISSING'].includes(value)?'warning':value==='SUCCESS'?'success':'info'}
const siteTotal=ref(0),groupTotal=ref(0),siteQuery=ref(''),groupQuery=ref('')
let sitePage=1,groupPage=1,siteGeneration=0,groupGeneration=0
async function searchSites(query:string,more=false){const generation=++siteGeneration;siteQuery.value=query;sitePage=more?sitePage+1:1;const {data}=await http.get('/api/admin/api/gateway/sites',{params:{query,page:sitePage,size:100}});if(generation!==siteGeneration)return;siteOptions.value=more?[...siteOptions.value,...data.items]:data.items;siteTotal.value=data.total}
async function searchGroups(query:string,more=false){const generation=++groupGeneration;groupQuery.value=query;groupPage=more?groupPage+1:1;const {data}=await http.get('/api/admin/api/gateway/groups',{params:{query,siteId:siteId.value,page:groupPage,size:100}});if(generation!==groupGeneration)return;groupOptions.value=more?[...groupOptions.value,...data.items]:data.items;groupTotal.value=data.total}
async function options(){await Promise.all([searchSites(''),searchGroups('')])}
async function load(){loading.value=true;error.value='';try{const path=tab.value==='channels'?'groups':tab.value==='records'?recordKind.value:'models';const{data}=await http.get('/api/admin/api/gateway/'+path,{params:{siteId:siteId.value,groupId:groupId.value,query:query.value,state:modelState.value,page:paging.page,size:paging.size,all:paging.all}});rows.value=data.items;summary.value=(await http.get('/api/admin/api/gateway/summary',{params:{siteId:siteId.value,groupId:groupId.value}})).data;paging.total=data.total;paging.page=data.page;selected.value=[]}catch(e){if(paging.all){paging.all=false;await load()}else error.value=getHttpErrorMessage(e,'读取失败')}finally{loading.value=false}}
async function reloadAll(){await options();await load()}
function filterChanged(){paging.page=1;load()}
async function siteChanged(){groupId.value=undefined;await options();filterChanged()}
function tabChanged(){router.replace({query:{...route.query,tab:tab.value}});filterChanged()}
const pendingGroupJobs=ref<string[]>([])
async function checkGroupJobs(){for(const id of [...pendingGroupJobs.value]){try{const {data}=await http.get(`/api/admin/api/gateway/jobs/${id}`);if(!['QUEUED','RUNNING'].includes(data.status)){pendingGroupJobs.value=pendingGroupJobs.value.filter(x=>x!==id);if(data.status==='SUCCESS')ElMessage.success(data.message);else if(data.status==='PARTIAL')ElMessage.warning(data.message);else ElMessage.error(data.message||'分组同步失败');await reloadAll()}}catch{pendingGroupJobs.value=pendingGroupJobs.value.filter(x=>x!==id)}}}
async function syncGroups(id?:number){if(!id)return;working.value=true;try{const {data}=await http.post(`/api/admin/api/gateway/sites/${id}/sync-groups`);pendingGroupJobs.value.push(data.jobId);ElMessage.success('上游分组同步已提交，可在运行记录查看结果');await reloadAll()}catch(e){ElMessage.error(getHttpErrorMessage(e,'分组同步失败'))}finally{working.value=false}}
async function synchronize(id?:number){working.value=true;try{const {data}=await http.post('/api/admin/api/gateway/sync',{siteId:siteId.value,groupId:typeof id==='number'?id:groupId.value});pendingGroupJobs.value.push(...data.jobs.filter((j:any)=>j.siteId&&j.jobId).map((j:any)=>j.jobId));const failures=data.jobs.filter((j:any)=>j.error);if(failures.length)ElMessage.error(failures.map((j:any)=>`分组 ${j.groupId}：${j.error}`).join('；'));else ElMessage.success('同步任务已提交，可在运行记录查看进度');await load()}catch(e){ElMessage.error(getHttpErrorMessage(e,'提交失败'))}finally{working.value=false}}
function healthLabel(value:string){return ({CREDENTIAL_MISSING:'待配置 Key',VERIFYING:'待核验',HEALTHY:'健康',UNTESTED:'待测试',DEGRADED:'测试异常',DISABLED:'认证失败'} as Record<string,string>)[value]||value||'待测试'}
async function test(row:any){working.value=true;try{const {data}=await http.post(`/api/admin/api/gateway/groups/${row.id}/test`,{},{timeout:180000});if(data.status==='SUCCESS')ElMessage.success(`测试成功：${data.model||''}`);else ElMessage.error(`测试失败：${data.error||healthLabel(data.healthStatus)}`)}catch(e){ElMessage.error(getHttpErrorMessage(e,'测试失败'))}finally{await load();working.value=false}}
function editPublicName(row:any){editGroup(row);settings.inheritDisplay=false}
function editSite(){const s=siteOptions.value.find(x=>x.id===siteId.value);if(!s)return;settingsId.value=s.id;settingsKind.value='site';Object.assign(settings,{name:s.name,publicName:s.public_name||'',publicCode:s.public_code||'',badgeText:s.badge_text||'',badgeColor:s.badge_color||'#2563eb',apiKey:''});Object.assign(accountAuth,{email:'',password:'',totpCode:'',emailPreview:s.account_email_preview||'',authenticated:!!s.account_authenticated,status:s.account_auth_status||'ANONYMOUS',lastError:s.account_auth_error||''});settingsError.value='';settingsOpen.value=true}
function editGroup(row:any){settingsId.value=row.id;settingsKind.value='group';Object.assign(settings,{name:row.name,enabled:!!row.enabled,syncEnabled:!!row.sync_enabled,apiKey:'',publicName:row.public_name||'',publicCode:row.public_code||'',badgeText:row.badge_text||'',badgeColor:row.badge_color||'#2563eb',inheritDisplay:!row.display_mapping_id});settingsError.value='';settingsOpen.value=true}
async function saveSettings(){working.value=true;settingsError.value='';try{await http.put(`/api/admin/api/gateway/${settingsKind.value==='site'?'sites':'groups'}/${settingsId.value}`,settings);settings.apiKey='';settingsOpen.value=false;await reloadAll()}catch(e){settingsError.value=getHttpErrorMessage(e,'保存失败')}finally{working.value=false}}
function accountStatusMessage(){if(accountAuth.status==='READY')return `账号目录已授权${accountAuth.emailPreview?'：'+accountAuth.emailPreview:''}`;if(accountAuth.status==='TWO_FACTOR_REQUIRED')return '请输入 AiAPIBank 两步验证码完成授权';if(accountAuth.status==='ERROR')return accountAuth.lastError||'账号授权已失效，请重新登录';return '当前使用匿名模型广场目录'}
function clearSettingsSecrets(){settings.apiKey='';accountAuth.password='';accountAuth.totpCode=''}
async function authorizeAiApiBank(){working.value=true;settingsError.value='';try{const payload=accountAuth.status==='TWO_FACTOR_REQUIRED'?{totpCode:accountAuth.totpCode}:{email:accountAuth.email,password:accountAuth.password};const{data}=await http.post(`/api/admin/api/gateway/sites/${settingsId.value}/aiapibank/authorize`,payload,{timeout:60000});accountAuth.password='';accountAuth.totpCode='';accountAuth.emailPreview=data.accountEmailPreview||accountAuth.emailPreview;accountAuth.authenticated=!!data.authenticated;accountAuth.status=data.status;if(data.requiresTwoFactor){ElMessage.warning('请输入两步验证码完成授权')}else{if(data.jobId)pendingGroupJobs.value.push(data.jobId);ElMessage.success('账号授权成功，专用分组同步已提交');await reloadAll()}}catch(e){settingsError.value=getHttpErrorMessage(e,'AiAPIBank 登录授权失败')}finally{accountAuth.password='';working.value=false}}
async function clearAiApiBankAuthorization(){working.value=true;settingsError.value='';try{await http.delete(`/api/admin/api/gateway/sites/${settingsId.value}/aiapibank/authorization`);Object.assign(accountAuth,{email:'',password:'',totpCode:'',emailPreview:'',authenticated:false,status:'ANONYMOUS',lastError:''});ElMessage.success('账号授权已移除，后续使用匿名目录');await reloadAll()}catch(e){settingsError.value=getHttpErrorMessage(e,'移除账号授权失败')}finally{working.value=false}}
async function publish(){working.value=true;try{batchResults.value=(await http.post('/api/admin/api/gateway/models/'+(modelState.value==='pending-import'?'import':'publish'),modelState.value==='pending-import'?selected.value.map(x=>({channelId:x.channel_id,model:x.upstream_model_name})):{ids:selected.value.map(x=>x.id)})).data;batchOpen.value=true;await load()}catch(e){ElMessage.error(getHttpErrorMessage(e,'发布失败'))}finally{working.value=false}}
let timer:ReturnType<typeof setInterval>|undefined
onMounted(async()=>{await reloadAll();timer=setInterval(()=>{if(pendingGroupJobs.value.length)checkGroupJobs();if(!loading.value&&rows.value.some(r=>['QUEUED','RUNNING'].includes(r.status||r.sync_status)))load()},3000)})
onBeforeUnmount(()=>{if(timer)clearInterval(timer)})
</script>
<style scoped>
.gateway-workbench { display:grid; gap:16px; }.heading,.actions,.filters { display:flex; gap:12px; align-items:center; flex-wrap:wrap; }.heading{justify-content:space-between}.heading h2{margin:0}.heading p{color:var(--el-text-color-secondary)}.filters .el-select{width:210px}.filters .el-input{max-width:250px}.panel{min-width: 0;padding:18px;border:1px solid var(--el-border-color);border-radius:12px;background:var(--el-bg-color)}.failure-text{color:var(--el-color-danger)}small{color:var(--el-text-color-secondary)}
</style>
