<template><el-dialog v-model="open" title="模型路由与定价" width="min(1000px,96vw)"><el-form v-if="model" label-position="top"><div class="fields"><el-form-item label="公开模型名称"><el-input v-model="model.publicModelName"/></el-form-item><el-form-item label="上游模型 ID"><el-input v-model="model.channelModelName"/></el-form-item><el-form-item label="路由优先级"><el-input-number v-model="model.priority" :min="0"/></el-form-item><el-form-item label="计费单位"><el-select v-model="model.pricingUnit"><el-option v-for="unit in ['TOKEN','TASK','IMAGE','SECOND','MINUTE','CHARACTER']" :key="unit" :value="unit" :label="unit"/></el-select></el-form-item></div><p>金额单位为 USD，Token 价格按百万计。手工保存售价后将保护该模型，自动同步继续更新采购价。</p><div class="fields"><el-form-item v-for="field in fields" :key="field.key" :label="field.label"><el-input-number v-model="model[field.key]" :min="0" :precision="8"/></el-form-item></div><el-form-item label="价格核验状态"><el-select v-model="model.pricingStatus"><el-option label="待配置" value="PENDING"/><el-option label="已人工核验" value="VERIFIED"/></el-select></el-form-item><el-form-item label="计费启用"><el-switch v-model="model.billingEnabled"/></el-form-item><PagedTable :data="model.priceTiers||[]" list-id="gateway-model-price-tiers"><el-table-column prop="tierName" label="阶梯" min-width="120"/><el-table-column prop="maxContextTokens" label="上下文上限" width="120"/><el-table-column v-for="dimension in dimensions" :key="dimension.key" :label="dimension.label" min-width="195"><template #default="{row}"><small>采购</small><el-input-number v-model="row['cost'+dimension.key+'Price']" :min="0" :precision="8"/><small>销售</small><el-input-number v-model="row['sale'+dimension.key+'Price']" :min="0" :precision="8"/></template></el-table-column></PagedTable></el-form><el-alert v-if="error" :title="error" type="error" :closable="false"/><template #footer><el-button type="primary" :loading="busy" @click="save">保存为手工定价</el-button></template></el-dialog></template>
<script setup lang="ts">
import {ref} from 'vue'
import PagedTable from './PagedTable.vue'
import http,{getHttpErrorMessage} from '../utils/http'
const emit=defineEmits<{changed:[]}>()
const open=ref(false),busy=ref(false),error=ref(''),model=ref<any>(null)
const fields=[{key:'inputCostPerMillion',label:'输入采购 / 百万 Token'},{key:'inputPricePerMillion',label:'输入售价 / 百万 Token'},{key:'outputCostPerMillion',label:'输出采购 / 百万 Token'},{key:'outputPricePerMillion',label:'输出售价 / 百万 Token'},{key:'cachedCostPerMillion',label:'缓存采购 / 百万 Token'},{key:'cachedPricePerMillion',label:'缓存售价 / 百万 Token'},{key:'costUnitPrice',label:'采购 / 计费单位'},{key:'saleUnitPrice',label:'售价 / 计费单位'}]
const dimensions=[{key:'Input',label:'输入'},{key:'Output',label:'输出'},{key:'CacheRead',label:'缓存读取'},{key:'CacheWrite',label:'缓存写入'},{key:'CacheWrite1h',label:'缓存写入1小时'},{key:'ImageInput',label:'图像输入'},{key:'ImageOutput',label:'图像输出'},{key:'PerRequest',label:'按次'}]
async function show(id:number){open.value=true;error.value='';model.value=null;try{model.value=(await http.get(`/api/admin/api/gateway/models/${id}/configuration`)).data}catch(e){error.value=getHttpErrorMessage(e,'读取失败')}}
async function save(){if(!model.value)return;busy.value=true;error.value='';try{model.value.billingMode=model.value.billingEnabled?'PAID':'DISABLED';await http.put(`/api/admin/api/models/${model.value.id}`,model.value);open.value=false;emit('changed')}catch(e){error.value=getHttpErrorMessage(e,'保存失败')}finally{busy.value=false}}
defineExpose({show})
</script>
<style scoped>.fields{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}small{display:block;color:var(--el-text-color-secondary)}</style>
