<template>
  <div class="profile-center" v-loading="loading">
    <section class="console-panel profile-summary">
      <div class="profile-avatar"><img v-if="profile.avatarPath" :src="profile.avatarPath" alt="用户头像"><span v-else>{{ initial }}</span><label><input type="file" accept="image/jpeg,image/png,image/webp" @change="uploadAvatar">更换头像</label></div>
      <div><h2>{{ profile.displayName || profile.username }}</h2><p>账号 ID：{{ profile.id }} · 注册于 {{ formatDate(profile.createdAt) }}</p><el-progress :percentage="completeness" :stroke-width="8"/><small>账户完整度 {{ completeness }}%</small></div>
    </section>
    <section class="profile-grid">
      <article class="console-panel"><h3>基本信息</h3><el-form label-position="top"><el-form-item label="显示名称"><el-input v-model="basics.displayName" maxlength="80"/></el-form-item><el-form-item label="语言"><el-select v-model="basics.locale"><el-option label="简体中文" value="zh-CN"/><el-option label="English" value="en-US"/></el-select></el-form-item><el-form-item label="时区"><el-select v-model="basics.timezone" filterable><el-option label="Asia/Shanghai" value="Asia/Shanghai"/><el-option label="Asia/Tokyo" value="Asia/Tokyo"/><el-option label="UTC" value="UTC"/></el-select></el-form-item><el-button type="primary" :loading="saving" @click="saveBasics">保存偏好</el-button></el-form></article>
      <article class="console-panel"><h3>联系方式</h3><p class="profile-tip">新建 Key、充值和购买前需完成{{ requiresPhone?'邮箱和手机':'邮箱' }}验证。</p><el-form label-position="top"><el-form-item label="邮箱"><el-input v-model="contacts.email"><template #append><span>{{ profile.emailVerifiedAt?'已验证':'未验证' }}</span></template></el-input></el-form-item><el-form-item label="邮箱验证码"><div class="profile-code-row"><el-input v-model="contacts.emailCode" maxlength="6"/><el-button @click="sendCode('email')">发送</el-button></div></el-form-item><el-form-item v-if="requiresPhone" label="手机号"><el-input v-model="contacts.phone"><template #append><span>{{ profile.phoneVerifiedAt?'已验证':'未验证' }}</span></template></el-input></el-form-item><el-form-item v-if="requiresPhone" label="短信验证码"><div class="profile-code-row"><el-input v-model="contacts.phoneCode" maxlength="6"/><el-button @click="sendCode('phone')">发送</el-button></div></el-form-item><el-button type="primary" @click="saveContacts">验证并保存</el-button></el-form></article>
      <article class="console-panel"><h3>登录安全</h3><el-form label-position="top"><el-form-item label="当前密码"><el-input v-model="password.currentPassword" type="password" show-password/></el-form-item><el-form-item label="新密码"><el-input v-model="password.newPassword" type="password" show-password placeholder="10–72 字节，包含字母和数字"/></el-form-item><el-button @click="changePassword">设置 / 修改密码</el-button></el-form><div class="oauth-bindings"><b>第三方账号</b><span class="oauth-binding" v-for="item in bindings" :key="item.id"><el-tag>{{ item.provider }}</el-tag><el-button link type="danger" @click="unlinkOAuth(item.provider)">解绑</el-button></span><el-button v-if="!isBound('github')" size="small" @click="bindOAuth('github')">绑定 GitHub</el-button><el-button v-if="!isBound('google')" size="small" @click="bindOAuth('google')">绑定 Google</el-button></div></article>
      <article class="console-panel sessions-panel"><div class="profile-section-head"><div><h3>登录设备</h3><p>可撤销丢失或不再使用的设备会话。</p></div><el-button size="small" @click="revokeOthers">退出其他设备</el-button></div><div class="session-list"><div v-for="item in sessions" :key="item.id"><span><b>{{ item.device || item.client }}</b><small>{{ item.current?'当前设备':'其他设备' }} · {{ formatDate(item.lastActiveAt||item.createdAt) }}</small></span><el-button v-if="!item.current" link type="danger" @click="revoke(item.id)">退出</el-button></div></div></article>
      <article class="console-panel sessions-panel"><div class="profile-section-head"><div><h3>登录 IP 历史</h3><p>当前地址：{{ profile.currentLoginIp || '未知' }}。新的未信任地址登录时需要邮箱验证码。</p></div></div><div class="session-list"><div v-for="item in profile.loginIpHistory||[]" :key="item.id"><span><b>{{ item.ip_preview || item.ipPreview }}</b><small>首次 {{ formatDate(item.first_seen_at||item.firstSeenAt) }} · 最近 {{ formatDate(item.last_seen_at||item.lastSeenAt) }}</small></span><el-button v-if="!(item.revoked_at||item.revokedAt)" link type="danger" @click="revokeIp(item.id)">撤销信任</el-button><el-tag v-else type="info">已撤销</el-tag></div></div></article>
    </section>
  </div>
</template>
<script setup lang="ts">
import {computed,onMounted,reactive,ref} from 'vue';import {ElMessage} from 'element-plus';import http,{getHttpErrorMessage} from '@/utils/http';import {getUser,setAuth,getToken,getRefreshToken} from '@/utils/auth';import {saveOAuthState,type OAuthProvider} from '@/utils/oauthState'
const loading=ref(false),saving=ref(false),profile=reactive<any>({}),sessions=ref<any[]>([]),bindings=ref<any[]>([]),verificationMode=ref<'EMAIL_ONLY'|'EMAIL_AND_PHONE'>('EMAIL_AND_PHONE'),basics=reactive({displayName:'',locale:'zh-CN',timezone:'Asia/Shanghai'}),contacts=reactive({email:'',emailCode:'',phone:'',phoneCode:''}),password=reactive({currentPassword:'',newPassword:''})
const requiresPhone=computed(()=>verificationMode.value==='EMAIL_AND_PHONE')
const initial=computed(()=>String(profile.displayName||profile.username||'用').slice(0,1).toUpperCase()),completeness=computed(()=>{const fields=[profile.displayName,profile.avatarPath,profile.emailVerifiedAt,profile.timezone];if(requiresPhone.value)fields.push(profile.phoneVerifiedAt);return Math.round(fields.filter(Boolean).length/fields.length*100)})
async function load(){loading.value=true;try{const [p,s,b,v]=await Promise.all([http.get('/api/user/profile'),http.get('/api/user/profile/sessions'),http.get('/api/user/profile/oauth-bindings'),http.get('/api/auth/verification/policy')]);Object.assign(profile,p.data||{});if(v.data?.mode==='EMAIL_ONLY'||v.data?.mode==='EMAIL_AND_PHONE')verificationMode.value=v.data.mode;Object.assign(basics,{displayName:profile.displayName||'',locale:profile.locale||'zh-CN',timezone:profile.timezone||'Asia/Shanghai'});Object.assign(contacts,{email:profile.email||'',emailCode:'',phone:profile.phone||'',phoneCode:''});sessions.value=s.data||[];bindings.value=b.data||[]}catch(e){ElMessage.error(getHttpErrorMessage(e,'个人信息加载失败'))}finally{loading.value=false}}
async function saveBasics(){saving.value=true;try{Object.assign(profile,(await http.patch('/api/user/profile',basics)).data||{});const u=getUser();if(u&&getToken())setAuth(getToken()!,{...u,displayName:profile.displayName,avatarPath:profile.avatarPath},getRefreshToken()||undefined);ElMessage.success('个人偏好已保存')}catch(e){ElMessage.error(getHttpErrorMessage(e,'保存失败'))}finally{saving.value=false}}
async function uploadAvatar(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;const data=new FormData();data.append('file',file);try{const r=await http.post('/api/user/profile/avatar',data);profile.avatarPath=r.data?.avatarPath;await saveBasics()}catch(e){ElMessage.error(getHttpErrorMessage(e,'头像上传失败'))}}
async function sendCode(channel:'email'|'phone'){const recipient=channel==='email'?contacts.email:contacts.phone;try{const r=await http.post(`/api/auth/verification/${channel}/send`,{recipient,purpose:'CHANGE'});if(r.data?.debugCode)ElMessage.info(`本地验证码：${r.data.debugCode}`);else ElMessage.success('验证码已发送')}catch(e){ElMessage.error(getHttpErrorMessage(e,'发送失败'))}}
async function saveContacts(){try{Object.assign(profile,(await http.put('/api/user/profile/contacts',contacts)).data||{});ElMessage.success('联系方式已更新')}catch(e){ElMessage.error(getHttpErrorMessage(e,'验证或保存失败'))}}
async function changePassword(){try{await http.put('/api/user/profile/password',password);password.currentPassword='';password.newPassword='';ElMessage.success('密码已更新')}catch(e){ElMessage.error(getHttpErrorMessage(e,'密码更新失败'))}}
async function unlinkOAuth(provider:string){try{await http.delete(`/api/user/profile/oauth-bindings/${encodeURIComponent(provider)}`);bindings.value=bindings.value.filter(item=>String(item.provider).toLowerCase()!==String(provider).toLowerCase());ElMessage.success('第三方账号已解绑')}catch(e){ElMessage.error(getHttpErrorMessage(e,'解绑失败'))}}
const isBound=(provider:OAuthProvider)=>bindings.value.some(item=>String(item.provider).toLowerCase()===provider)
async function bindOAuth(provider:OAuthProvider){try{const res=await http.get('/api/oauth/authorize',{params:{provider}});const url=String(res.data?.url||''),state=String(res.data?.state||'');const parsed=new URL(url);if(parsed.protocol!=='https:'||parsed.searchParams.get('state')!==state)throw new Error('授权地址校验失败');saveOAuthState(provider,state,'/console/profile');window.location.assign(parsed.toString())}catch(e){ElMessage.error(getHttpErrorMessage(e,'启动第三方绑定失败'))}}
async function revoke(id:number){await http.delete(`/api/user/profile/sessions/${id}`);sessions.value=sessions.value.filter(item=>item.id!==id);ElMessage.success('设备已退出')};async function revokeOthers(){await http.delete('/api/user/profile/sessions');await load();ElMessage.success('其他设备已退出')}
async function revokeIp(id:number){try{await http.delete(`/api/user/login-ips/${id}/trust`);await load();ElMessage.success('该 IP 的信任已撤销')}catch(e){ElMessage.error(getHttpErrorMessage(e,'撤销失败'))}}
const formatDate=(v:any)=>v?new Date(v).toLocaleString():'暂无';onMounted(load)
</script>
<style scoped>.profile-center{display:grid;gap:16px}.profile-summary{display:grid;grid-template-columns:auto minmax(0,1fr);align-items:center;gap:20px}.profile-avatar{display:grid;justify-items:center;gap:8px}.profile-avatar img,.profile-avatar>span{display:grid;width:82px;height:82px;place-items:center;border-radius:24px;object-fit:cover;background:#dcecff;color:#1456a8;font-size:30px;font-weight:800}.profile-avatar label{color:#1761bd;font-size:12px;cursor:pointer}.profile-avatar input{display:none}.profile-summary h2{margin:0}.profile-summary p,.profile-summary small,.profile-tip,.profile-section-head p{color:#687c96;font-size:12px}.profile-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.profile-grid article h3{margin:0 0 14px}.profile-code-row{display:grid;width:100%;grid-template-columns:minmax(0,1fr) auto;gap:8px}.oauth-bindings,.oauth-binding{display:flex;align-items:center;flex-wrap:wrap;gap:8px}.oauth-bindings{margin-top:18px;color:#667a94;font-size:12px}.sessions-panel{grid-column:1/-1}.profile-section-head{display:flex;justify-content:space-between;gap:12px}.profile-section-head h3,.profile-section-head p{margin:0}.session-list{display:grid;margin-top:12px}.session-list>div{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 0;border-top:1px solid #e4edf8}.session-list span{display:grid}.session-list small{color:#71839a}@media(max-width:800px){.profile-grid{grid-template-columns:1fr}.sessions-panel{grid-column:auto}}@media(max-width:520px){.profile-summary{grid-template-columns:1fr}.profile-section-head{align-items:flex-start;flex-direction:column}}</style>
